(() => {
  'use strict';
  const BRAND_ORDER=['Josam','Car-O-Liner','BlackHawk'];
  const MANAGER_ORDER=['Sergej','Mindaugas Deikus','Ruslan Sollano','Michal Adamiec'];
  const BALTICS_SOUTH=new Set(['Lithuania','Latvia','Estonia','Greece','Cyprus']);
  const JOSAM_EXCLUDED=new Set(['Austria','Czechia','Slovakia']);
  const usd=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
  let data=[],period={year:null,month:null};
  const $=id=>document.getElementById(id),n=v=>Number.isFinite(Number(v))?Number(v):0;
  const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>usd.format(n(v)),signed=v=>(n(v)>=0?'+':'')+money(v),gapClass=v=>n(v)>=0?'good':'bad';
  const mn=m=>['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m]||String(m||'');
  const brandOf=v=>{const s=String(v||'').trim().toLowerCase();if(s==='josam')return'Josam';if(s==='car-o-liner'||s==='caroliner')return'Car-O-Liner';if(s==='blackhawk'||s==='black hawk')return'BlackHawk';return null};
  function ownerFor(r){const b=brandOf(r.Brand),c=String(r.CtyDes||r.Country||'').trim(),d=String(r.Director||'').trim();if(!b||!c)return null;if(b==='Josam'&&JOSAM_EXCLUDED.has(c))return null;if(d==='Export')return'Ruslan Sollano';if(d!=='Europe East')return null;if(c==='Austria')return b==='Josam'?null:'Sergej';if(BALTICS_SOUTH.has(c))return'Mindaugas Deikus';if(c==='Bulgaria')return'Ruslan Sollano';return'Michal Adamiec'}
  async function ensureXlsx(){if(globalThis.XLSX)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=res;s.onerror=()=>rej(new Error('XLSX reader could not be loaded'));document.head.appendChild(s)})}
  async function loadFile(file){const status=$('collisionStatus');try{status.textContent='Reading file…';await ensureXlsx();const buf=await file.arrayBuffer();status.textContent='Reading Collision data…';await new Promise(r=>setTimeout(r,20));const wb=XLSX.read(buf,{type:'array',dense:true,cellDates:false,sheets:['_002_TableCreation']});const ws=wb.Sheets['_002_TableCreation'];if(!ws)throw new Error('Sheet _002_TableCreation not found');const rows=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true});let y=-Infinity,m=-Infinity;for(const r of rows){if(r['Sales Status']==='Actual'){const yy=n(r.SnaponYear),mm=n(r.SnaponMonth);if(yy>y||(yy===y&&mm>m)){y=yy;m=mm}}}if(!Number.isFinite(y)||!Number.isFinite(m))throw new Error('Current month not found');period={year:y,month:m};const aop=`${y} AOP`,act=`${y} ACT`;data=[];for(const r of rows){const st=String(r['Sales Status']||''),yy=n(r.SnaponYear),mm=n(r.SnaponMonth);if(![aop,act,'Actual','Ord0','Ord1'].includes(st))continue;const b=brandOf(r.Brand),manager=ownerFor(r);if(!b||!manager)continue;data.push({manager,country:String(r.CtyDes||r.Country||'').trim(),brand:b,status:st,year:yy,month:mm,value:n(r['Net Price Extended'])})}status.textContent=`Loaded · ${file.name} · ${mn(m)} ${y} · USD`;render()}catch(e){console.error(e);status.textContent='Load error: '+(e?.message||String(e))}}
  function metric(rows){const aop=`${period.year} AOP`,act=`${period.year} ACT`,cm=period.month,cy=period.year;let aopM=0,actual=0,o0=0,o1=0,aopY=0,closed=0;for(const r of rows){if(r.year!==cy)continue;if(r.status===aop){if(r.month===cm)aopM+=r.value;if(r.month<=cm)aopY+=r.value}else if(r.status===act&&r.month<cm)closed+=r.value;else if(r.status==='Actual'&&r.month===cm)actual+=r.value;else if(r.status==='Ord0'&&r.month===cm)o0+=r.value;else if(r.status==='Ord1'&&r.month===cm)o1+=r.value}const forecast=actual+o0+o1,ytdActual=closed+actual,ytdForecast=ytdActual+o0+o1;return{aopM,actual,o0,o1,forecast,gapM:forecast-aopM,aopY,ytdActual,ytdForecast,gapY:ytdForecast-aopY}}
  function add(a,b){const o={};for(const k of ['aopM','actual','o0','o1','forecast','gapM','aopY','ytdActual','ytdForecast','gapY'])o[k]=n(a[k])+n(b[k]);return o}
  function head(){return `<tr class="group"><th colspan="2">SCOPE</th><th colspan="6" class="month">${mn(period.month).toUpperCase()} ${period.year}</th><th colspan="4" class="year">YTD ${period.year}</th></tr><tr><th>Owner / Country</th><th>Brand</th><th class="num sepM">AOP</th><th class="num">Actual</th><th class="num">Ord0</th><th class="num">Ord1</th><th class="num">Forecast</th><th class="num">Gap</th><th class="num sepY">AOP YTD</th><th class="num">Actual YTD</th><th class="num">Forecast YTD</th><th class="num">Gap YTD</th></tr>`}
  function row(label,b,x,cls=''){return `<tr class="${cls}"><td>${safe(label)}</td><td><span class="tag">${safe(b)}</span></td><td class="num sepM">${money(x.aopM)}</td><td class="num">${money(x.actual)}</td><td class="num">${money(x.o0)}</td><td class="num">${money(x.o1)}</td><td class="num"><b>${money(x.forecast)}</b></td><td class="num ${gapClass(x.gapM)}"><b>${signed(x.gapM)}</b></td><td class="num sepY">${money(x.aopY)}</td><td class="num">${money(x.ytdActual)}</td><td class="num"><b>${money(x.ytdForecast)}</b></td><td class="num ${gapClass(x.gapY)}"><b>${signed(x.gapY)}</b></td></tr>`}
  function render(){if(!data.length)return;const mgr=$('collisionManager').value,br=$('collisionBrand').value;const f=data.filter(r=>(mgr==='ALL'||r.manager===mgr)&&(br==='ALL'||r.brand===br)),t=metric(f);$('collisionKpis').innerHTML=`<div class="kpi"><small>Month AOP</small><b>${money(t.aopM)}</b></div><div class="kpi"><small>Actual</small><b>${money(t.actual)}</b></div><div class="kpi"><small>Ord0 + Ord1</small><b>${money(t.o0+t.o1)}</b></div><div class="kpi"><small>Month Forecast</small><b>${money(t.forecast)}</b><em class="${gapClass(t.gapM)}">${signed(t.gapM)} vs AOP</em></div><div class="kpi"><small>YTD Forecast</small><b>${money(t.ytdForecast)}</b></div><div class="kpi"><small>YTD Gap</small><b class="${gapClass(t.gapY)}">${signed(t.gapY)}</b><em>vs ${money(t.aopY)} AOP</em></div>`;const bt=$('brandTable');bt.querySelector('thead').innerHTML=head();let bh='',bm={};for(const b of BRAND_ORDER){bm[b]=metric(f.filter(r=>r.brand===b));bh+=row('Europe East',b,bm[b])}bh+=row('Europe East','COL + BlackHawk',add(bm['Car-O-Liner'],bm['BlackHawk']),'total');bt.querySelector('tbody').innerHTML=bh;const dt=$('detailTable');dt.querySelector('thead').innerHTML=head();let dh='';for(const m of (mgr==='ALL'?MANAGER_ORDER:[mgr])){const mr=f.filter(r=>r.manager===m);if(!mr.length)continue;dh+=`<tr class="mgr"><td colspan="12">${safe(m)}</td></tr>`;for(const c of [...new Set(mr.map(r=>r.country))].sort()){const cr=mr.filter(r=>r.country===c);for(const b of (br==='ALL'?BRAND_ORDER:[br]).filter(b=>cr.some(r=>r.brand===b)))dh+=row(c,b,metric(cr.filter(r=>r.brand===b)))}dh+=row(m,'TOTAL',metric(mr),'total')}dt.querySelector('tbody').innerHTML=dh||'<tr><td colspan="12">No matching data</td></tr>'}
  $('collisionLoad').onclick=()=>$('collisionFile').click();$('collisionFile').onchange=e=>{const f=e.target.files?.[0];if(f)loadFile(f);e.target.value=''};$('collisionManager').onchange=render;$('collisionBrand').onchange=render;
})();