(()=>{
const E=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const P=v=>Number.isFinite(v)?new Intl.NumberFormat('de-DE',{style:'percent',maximumFractionDigits:1}).format(v):'—';
const C=v=>v>=0?'good':'bad';
function sum(a){return a.reduce((x,r)=>{for(const k of ['mtd','o1','est','plan','ytd','pytd'])x[k]+=Number(r[k]||0);return x},{mtd:0,o1:0,est:0,plan:0,ytd:0,pytd:0})}
function goalBox(title,actual,target,gap,extra=''){
 const ach=target?actual/target:NaN;
 return `<div class="goalBox"><div class="goalTitle">${title}</div><div class="goalMain"><span>${E.format(actual)}</span><small>of ${E.format(target)}</small></div><div class="goalMeta"><b>${target?P(ach):'—'}</b><strong class="${C(gap)}">${gap>=0?'+':''}${E.format(gap)}</strong></div>${extra}</div>`;
}
function apply(){
 if(typeof data==='undefined'||!Array.isArray(data)||!data.length)return;
 const sel=document.getElementById('manager')?.value||'ALL';
 const rows=sel==='ALL'?data:data.filter(r=>r.m===sel),a=sum(rows),mGap=a.mtd-a.plan,yGap=a.ytd-a.pytd,fGap=a.est-a.plan;
 const k=document.getElementById('kpis'); if(k){k.className='goalsGrid';k.innerHTML=`<section class="goalSection monthly"><div class="sectionHead"><span>MONTH</span><b>Current month target</b></div><div class="goalRow">${goalBox('Sales MTD',a.mtd,a.plan,mGap,`<div class="goalSub">Backlog Ord1 <b>${E.format(a.o1)}</b></div>`)}${goalBox('Forecast incl. Backlog',a.est,a.plan,fGap,`<div class="goalSub">Remaining after backlog <b class="${C(fGap)}">${fGap>=0?'+'+E.format(fGap):E.format(fGap)}</b></div>`)}</div></section><section class="goalSection annual"><div class="sectionHead"><span>YEAR</span><b>YTD target</b></div><div class="goalRow one">${goalBox('Sales YTD',a.ytd,a.pytd,yGap,`<div class="goalSub">${yGap>=0?'Above annual plan':'Missing to annual plan'} <b class="${C(yGap)}">${yGap>=0?'+':''}${E.format(yGap)}</b></div>`)}</div></section>`}
 const cards=document.getElementById('cards'); if(cards){const ms=[...new Set(rows.map(r=>r.m))];cards.innerHTML=ms.map(m=>{let x=sum(data.filter(r=>r.m===m)),mg=x.mtd-x.plan,fg=x.est-x.plan,yg=x.ytd-x.pytd;return `<div class="card managerGoal"><div class="managerName"><b>${m}</b><span>GM MTD ${typeof gm!=='undefined'&&gm[m]!=null?P(gm[m]):'—'}</span></div><div class="managerMonth"><span class="miniTitle">MONTH</span><div><small>MTD / Target</small><b>${E.format(x.mtd)} / ${E.format(x.plan)}</b></div><div><small>Backlog</small><b>${E.format(x.o1)}</b></div><div><small>Forecast</small><b>${E.format(x.est)}</b></div><div><small>Gap</small><b class="${C(fg)}">${fg>=0?'+':''}${E.format(fg)}</b></div></div><div class="managerYear"><span class="miniTitle">YEAR</span><div><small>YTD / Target</small><b>${E.format(x.ytd)} / ${E.format(x.pytd)}</b></div><div><small>YTD %</small><b>${x.pytd?P(x.ytd/x.pytd):'—'}</b></div><div><small>YTD Gap</small><b class="${C(yg)}">${yg>=0?'+':''}${E.format(yg)}</b></div></div></div>`}).join('')}
}
const style=document.createElement('style');style.textContent=`
.goalsGrid{display:grid;grid-template-columns:1.35fr .85fr;gap:10px;margin-bottom:10px}.goalSection{background:#fff;border:1px solid var(--line);border-radius:11px;overflow:hidden;box-shadow:0 4px 14px rgba(16,24,40,.045)}.goalSection.monthly{border-top:3px solid var(--red)}.goalSection.annual{border-top:3px solid var(--blue)}.sectionHead{display:flex;align-items:center;gap:8px;padding:8px 11px 5px;border-bottom:1px solid #edf0f2}.sectionHead span{font-size:9px;font-weight:900;letter-spacing:.08em;color:#fff;background:#222;padding:3px 6px;border-radius:4px}.monthly .sectionHead span{background:var(--red)}.annual .sectionHead span{background:var(--blue)}.sectionHead b{font-size:12px}.goalRow{display:grid;grid-template-columns:1fr 1fr;gap:0}.goalRow.one{grid-template-columns:1fr}.goalBox{padding:9px 12px}.goalBox+ .goalBox{border-left:1px solid #edf0f2}.goalTitle{font-size:9px;text-transform:uppercase;font-weight:850;color:#777d85}.goalMain{display:flex;align-items:baseline;gap:5px;margin-top:3px}.goalMain span{font-size:22px;font-weight:900;letter-spacing:-.03em}.goalMain small{font-size:10px;color:#8a8f96}.goalMeta{display:flex;justify-content:space-between;gap:8px;margin-top:3px}.goalMeta b{font-size:11px}.goalMeta strong{font-size:13px}.goalSub{margin-top:4px;font-size:10px;color:#7d828a}.managerGoal{display:grid;grid-template-columns:180px 1.45fr 1fr;align-items:stretch;min-height:66px;overflow:hidden}.managerName{padding:9px 10px;display:flex;flex-direction:column;justify-content:center;border-right:1px solid #e6e9ec}.managerName b{font-size:13px}.managerName span{font-size:9px;color:#7f848c;margin-top:2px}.managerMonth,.managerYear{display:grid;align-items:center;gap:10px;padding:7px 10px;position:relative}.managerMonth{grid-template-columns:48px 1.35fr 1fr 1fr 1fr;border-right:2px solid #dfe3e7}.managerYear{grid-template-columns:42px 1.5fr .7fr 1fr}.miniTitle{font-size:8px;font-weight:900;letter-spacing:.08em;color:#fff;border-radius:4px;padding:3px 5px;text-align:center}.managerMonth .miniTitle{background:var(--red)}.managerYear .miniTitle{background:var(--blue)}.managerMonth div,.managerYear div{min-width:0}.managerMonth small,.managerYear small{display:block;font-size:8px;text-transform:uppercase;color:#858a92;font-weight:800}.managerMonth b,.managerYear b{display:block;font-size:11.5px;margin-top:1px;white-space:nowrap}.countryTableSep{border-left:3px solid #dfe4ea!important}.good{color:var(--green)!important}.bad{color:#c72c33!important}
@media(max-width:1000px){.goalsGrid{grid-template-columns:1fr}.managerGoal{grid-template-columns:150px 1fr}.managerYear{grid-column:2;border-top:1px solid #edf0f2}.managerMonth{border-right:0}.managerName{grid-row:1/3}}@media(max-width:700px){.goalRow{grid-template-columns:1fr}.goalBox+.goalBox{border-left:0;border-top:1px solid #edf0f2}.managerGoal{display:block}.managerName,.managerMonth,.managerYear{border:0;border-bottom:1px solid #edf0f2}.managerMonth{grid-template-columns:42px repeat(2,1fr)}.managerYear{grid-template-columns:42px repeat(2,1fr)}}`;
document.head.appendChild(style);
const orig=window.renderTeam||renderTeam; window.renderTeam=function(){orig();setTimeout(apply,0)};
document.getElementById('manager')?.addEventListener('change',()=>setTimeout(apply,0));
const obs=new MutationObserver(()=>{if(!obs.busy){obs.busy=true;requestAnimationFrame(()=>{apply();obs.busy=false})}});let k=document.getElementById('kpis');if(k)obs.observe(k,{childList:true});
setTimeout(apply,300);
})();