(()=>{
const LIMIT=800;
let wbCache=null, customersReady=false, journalReady=false;
const E=typeof euro!=='undefined'?euro:new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const P=typeof pct==='function'?pct:(v=>Number.isFinite(v)?new Intl.NumberFormat('de-DE',{style:'percent',maximumFractionDigits:1}).format(v):'—');
const X=typeof esc==='function'?esc:(s=>String(s??''));
const $id=id=>document.getElementById(id);
function paint(){return new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))}
function cloneControl(id){const old=$id(id);if(!old)return null;const fresh=old.cloneNode(true);old.replaceWith(fresh);return fresh}
const oldK=$id('kpis');if(oldK){const freshK=oldK.cloneNode(true);oldK.replaceWith(freshK)}
const file=cloneControl('file');
const cm=cloneControl('customerManager'),cc=cloneControl('customerCountry'),cs=cloneControl('customerSearch');
const jm=cloneControl('journalManager'),jt=cloneControl('journalType'),js=cloneControl('journalSearch');
function managersList(){return [...new Set((data||[]).map(r=>r.m))]}
function fillManager(el){if(!el)return;const old=el.value,ms=managersList();el.innerHTML='<option value="ALL">All managers</option>'+ms.map(m=>`<option>${X(m)}</option>`).join('');if(ms.includes(old))el.value=old}
function customerPlaceholder(){const k=$id('customerKpis'),b=$id('customerBody');if(k)k.innerHTML='<div class="card miniKpi"><div class="label">Customers</div><div class="value">Open tab</div><div class="muted">Loads from selected Excel file</div></div>';if(b)b.innerHTML='<tr><td colspan="11" class="muted">Open the Customers tab to load customer details.</td></tr>'}
function journalPlaceholder(){const k=$id('journalKpis'),b=$id('journalBody');if(k)k.innerHTML='<div class="card miniKpi"><div class="label">Journal</div><div class="value">Open tab</div><div class="muted">Loads on demand for performance</div></div>';if(b)b.innerHTML='<tr><td colspan="10" class="muted">Open the Sales Gross Margin Journal tab to load transactions.</td></tr>'}
function renderCustomersFast(){fillManager(cm);let mgr=cm?.value||'ALL',country=cc?.value||'ALL',q=(cs?.value||'').trim().toLowerCase();const allCountries=[...new Set((customers||[]).filter(x=>mgr==='ALL'||x.m===mgr).map(x=>x.c))].sort();if(cc){const old=cc.value;cc.innerHTML='<option value="ALL">All countries</option>'+allCountries.map(c=>`<option>${X(c)}</option>`).join('');cc.value=allCountries.includes(old)?old:'ALL';country=cc.value}const rows=(customers||[]).filter(x=>(mgr==='ALL'||x.m===mgr)&&(country==='ALL'||x.c===country)&&(!q||(x.name+' '+x.code).toLowerCase().includes(q)));const s=rows.reduce((a,x)=>{a.mtd+=x.mtd;a.o1+=x.o1;a.ytd+=x.ytd;a.gm+=x.gm;return a},{mtd:0,o1:0,ytd:0,gm:0});$id('customerKpis').innerHTML=`<div class="card miniKpi"><div class="label">Customers</div><div class="value">${rows.length}</div></div><div class="card miniKpi"><div class="label">Sales MTD</div><div class="value">${E.format(s.mtd)}</div></div><div class="card miniKpi"><div class="label">Backlog Ord1</div><div class="value">${E.format(s.o1)}</div></div><div class="card miniKpi"><div class="label">GM MTD %</div><div class="value">${P(s.mtd?s.gm/s.mtd:null)}</div></div>`;let html='',lastM='',lastC='';for(const x of rows.slice(0,LIMIT)){if(x.m!==lastM){html+=`<tr class="groupRow"><td colspan="11">${X(x.m)}</td></tr>`;lastM=x.m;lastC=''}if(x.c!==lastC){html+=`<tr class="countryGroup"><td></td><td colspan="10">${X(x.c)}</td></tr>`;lastC=x.c}html+=`<tr><td></td><td></td><td><b>${X(x.name)}</b></td><td>${X(x.code)}</td><td class="num">${E.format(x.mtd)}</td><td class="num">${E.format(x.o1)}</td><td class="num">${E.format(x.est||x.mtd+x.o1)}</td><td class="num">${E.format(x.ytd)}</td><td class="num">${E.format(x.gm)}</td><td class="num">${P(x.gmp)}</td><td class="num">${E.format(x.oe)}</td></tr>`}if(rows.length>LIMIT)html+=`<tr><td colspan="11" class="muted">Showing first ${LIMIT} of ${rows.length}. Use filters or search to narrow the list.</td></tr>`;$id('customerBody').innerHTML=html||'<tr><td colspan="11">No matching customers</td></tr>'}
function renderJournalFast(){fillManager(jm);let mgr=jm?.value||'ALL',type=jt?.value||'ALL',q=(js?.value||'').trim().toLowerCase();const rows=(journal||[]).filter(x=>(mgr==='ALL'||x.m===mgr)&&(type==='ALL'||x.type===type)&&(!q||(x.customer+' '+x.part+' '+x.desc+' '+x.c).toLowerCase().includes(q)));const s=rows.reduce((a,x)=>{a.sales+=x.sales;a.gm+=x.gm;return a},{sales:0,gm:0});$id('journalKpis').innerHTML=`<div class="card miniKpi"><div class="label">Transactions</div><div class="value">${rows.length}</div></div><div class="card miniKpi"><div class="label">Sales</div><div class="value">${E.format(s.sales)}</div></div><div class="card miniKpi"><div class="label">Gross Margin</div><div class="value">${E.format(s.gm)}</div></div><div class="card miniKpi"><div class="label">GM % weighted</div><div class="value">${P(s.sales?s.gm/s.sales:null)}</div></div>`;let html=rows.slice(0,LIMIT).map(x=>`<tr><td>${X(x.m)}</td><td>${X(x.c)}</td><td><b>${X(x.customer)}</b></td><td>${X(x.type)}</td><td>${X(x.date)}</td><td>${X(x.part)}</td><td>${X(x.desc)}</td><td class="num">${E.format(x.sales)}</td><td class="num ${x.gm<0?'bad':''}">${E.format(x.gm)}</td><td class="num ${x.gmp<0?'bad':''}">${P(x.gmp)}</td></tr>`).join('');if(rows.length>LIMIT)html+=`<tr><td colspan="10" class="muted">Showing first ${LIMIT} of ${rows.length}. Use filters or search to narrow the list.</td></tr>`;$id('journalBody').innerHTML=html||'<tr><td colspan="10">No matching transactions</td></tr>'}
async function ensureCustomers(){if(customersReady){renderCustomersFast();return}if(!wbCache){renderCustomersFast();return}try{$id('status').textContent='Loading customers…';await paint();customers=readCustomers(wbCache);customersReady=true;renderCustomersFast();$id('status').textContent='Customers loaded'}catch(e){$id('status').textContent='Customer load error: '+e.message}}
async function ensureJournal(){if(journalReady){renderJournalFast();return}if(!wbCache){renderJournalFast();return}try{$id('status').textContent='Loading journal…';await paint();journal=readJournal(wbCache);journalReady=true;renderJournalFast();$id('status').textContent='Journal loaded'}catch(e){$id('status').textContent='Journal load error: '+e.message}}
if(file)file.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{$id('status').textContent='Loading Excel…';await paint();const buf=await f.arrayBuffer();await paint();wbCache=XLSX.read(buf,{type:'array',cellDates:true});$id('status').textContent='Loading team overview…';await paint();data=readCountry(wbCache);gm=readGM(wbCache);customers=[];journal=[];customersReady=false;journalReady=false;$id('source').textContent='Loaded · '+f.name;renderTeam();customerPlaceholder();journalPlaceholder();$id('status').textContent='Updated'}catch(e){console.error(e);$id('status').textContent='Load error: '+(e?.message||e)}finally{e.target.value=''}});
cm?.addEventListener('change',()=>customersReady&&renderCustomersFast());cc?.addEventListener('change',()=>customersReady&&renderCustomersFast());cs?.addEventListener('input',()=>customersReady&&renderCustomersFast());jm?.addEventListener('change',()=>journalReady&&renderJournalFast());jt?.addEventListener('change',()=>journalReady&&renderJournalFast());js?.addEventListener('input',()=>journalReady&&renderJournalFast());document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='customers')ensureCustomers();if(b.dataset.tab==='journal')ensureJournal()}));
})();